title: LiileeFinTech
tagline: A text-focused Jekyll theme
description: A minimal, responsive, and feature-rich Jekyll theme for technical writing.
url: "https://liileefintech.github.io"
baseurl: ""

theme: jekyll-theme-chirpy
lang: en
timezone: Asia/Shanghai

github:
  username: liileefintech

twitter:
  username: Liileefintech

social:
  name: Liilee Fintech
  email: liileeofficial5@gmail.com
  links:
    - https://x.com/liileefintech
    - https://github.com/liileefintech

webmaster_verifications: {}

analytics: {}

pageviews: {}

theme_mode: light

cdn: "https://chirpy-img.netlify.app"

avatar: "/commons/avatar.jpg"
social_preview_image: ""

toc: true

comments:
  provider: disqus
  disqus:
    shortname: your_disqus_shortname
  utterances:
    repo: your_username/your_repo
    issue_term: pathname
  giscus:
    repo: your_username/your_repo
    repo_id: your_repo_id
    category: General
    category_id: your_category_id
    mapping: url
    reactions_enabled: true

assets:
  self_host:
    enabled: true
  env: production

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:
      - "/admin"

paginate: 10

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
